### ISSUE TITLE
Deleting html instead of replacing src

### ISSUE THREAD

**Issue by alexlime** [VFK/gulp-html-replace#19] opened 2014-10-23 14:44 UTC
Not working for me at all. 
It is just deleting everything in index.html file, starting from the part that have to be modified:

So this part:
``` html
<!-- build:js -->
<script src="../bower_components/jquery/dist/jquery.js"></script>
<script src="js/app.js"></script>
<!-- endbuild -->
```
And everything bellow it disappears.  

Here is my gulp task.
``` javascript
gulp.task('htmR', function() {
   gulp.src('app/index.html') 
      .pipe(htmlreplace({
         js: 'js/bundleB.min.js'
      }))
      .pipe(gulp.dest('app/'));
});
```

Is it compatible with node 0.10?

**Comment by charlescaron** [comment] 2015-01-12 22:09
I've been observing the behavior described above since we upgraded from 1.1.0 to 1.4.1. Parts of HTML are either skipped or entirely removed because of this issue.

It seems to be related to the way the parser handles line breaks. I was able to make things work with 1.4.1 by manually inserting line breaks after and before HTML comments marking the beginning and end of a snippet to replace.

**Comment by VFK** [comment] 2015-01-13 05:12
@charlescaron Could you provide that HTML file? Not copy and paste contents, just the file itself. I can't reproduce such behavior no matter what i try. I tried to create HTML files with different line breaks in different OS'es with no luck.

**Comment by JeroenNoten** [comment] 2015-01-13 12:13
FYI: also putting nothing between the start and end comment: `<!-- build:css --><!-- endbuild -->` results in everything below being deleted. Adding a line-break between them solves the issue.

**Comment by charlescaron** [comment] 2015-01-13 14:25
Here are the links to the source and the output I get with both 1.1.0 and 1.4.1. Note that I'm on Mac OS X, but I'm observing the same behavior on CentOS 6.3. 

Gulp version: 3.8.10
Node.js version: 0.10.32 

Source:
https://drive.google.com/file/d/0B0RIKmSzYfVCdHcxSXE5SVZCRmM/view?usp=sharing

Output with 1.1.0 (Good):
https://drive.google.com/file/d/0B0RIKmSzYfVCRUZOX3VfSk1EY2s/view?usp=sharing

Output with 1.4.1 (Wrong):
https://drive.google.com/file/d/0B0RIKmSzYfVCVTBDenE4ZUZYalk/view?usp=sharing

**Comment by VFK** [comment] 2015-01-13 15:38
Ah, finally, i see the problem now. Thanks @charlescaron ! Please test **1.4.2** and close this issue if it works

**Comment by VFK** [comment] 2015-01-13 15:50
@JeroenNoten noted, thank you

**Comment by charlescaron** [comment] 2015-01-13 17:52
1.4.2 works fine for me now, thanks!

**Closed** 2015-01-13 17:54 UTC
